<center><img src=https://lh3.googleusercontent.com/d/1EmH3Jks5CpJy0zK3JbkvJZkeqWtVcxhB width=600></center>

# Math with Python

Let's use Python to solve some math questions.

## Exercise 1

Create a null vector of size 10. (Hint: use numpy)

In [3]:
import numpy as np
vector = np.array([0]*10)
print(vector)

[0 0 0 0 0 0 0 0 0 0]


## Exercise 2

Create a null vector of size 10 and set the fifth value to be 1.

In [5]:
import numpy as np
vector = np.array([0]*10)
vector[4]=1
print(vector)

[0 0 0 0 1 0 0 0 0 0]


## Exercise 3

Create a 8x8 matrix and fill it with a checkerboard pattern (1 and 0 in alternating order).

In [8]:
matrix = [[value for _ in range(8) for value in (0,1) ] for _ in range(8) ]
print(matrix)

[[0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1], [0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1, 0, 1]]


## Exercise 4

Create a $5x5$ random matrix and normalize each column.

In [24]:
import random
import numpy as np
matrix = [[random.random() for _ in range(5) ] for _ in range(5) ]
# Normalize each column to range [0, 1]
min_vals = np.array(matrix).min(axis=0)
max_vals = np.array(matrix).max(axis=0)

normalized_data = (matrix - min_vals) / (max_vals - min_vals)
print(normalized_data)




[[0.14260533 0.63654849 0.69061094 0.88611794 0.46045809]
 [0.         0.89823143 1.         0.         0.        ]
 [0.46744738 0.75605175 0.39112214 1.         0.45543115]
 [0.78800256 1.         0.         0.075355   1.        ]
 [1.         0.         0.98106765 0.76019118 0.35664246]]


## Exercise 5

Multiply a $5x3$ matrix by a $3x2$ matrix (dot product).

In [86]:
import random
import numpy as np
A = np.random.randint(0, 3, size=(5, 3))

# Generate a 3x2 matrix with integers from 0 to 9
B = np.random.randint(0, 3, size=(3, 2))

def dotproduct(A,B):
    data = []
    for i in range(A.shape[0]):  
        for j in range(B.shape[1]):  # number of columns
            dotpr = []
            for num1, a in enumerate (A[i]):
                for num2, b in enumerate ( B[:,j]):
                    if num1==num2:
                        c = a*b
                        dotpr.append(c)
            data.append((i,j, sum(dotpr )))
    max_row = max(i for i, j, v in data)
    max_col = max(j for i, j, v in data)
    matrix = np.zeros((max_row + 1, max_col + 1))
    for row, col, val in data:
        matrix[row, col] = val
    return matrix
    
print(A)
print(B)
print("dotproduct(A,B)", dotproduct(A,B))                     
            

[[2 2 0]
 [1 1 0]
 [1 2 1]
 [0 2 0]
 [0 0 1]]
[[0 2]
 [1 0]
 [1 0]]
dotproduct(A,B) [[2. 4.]
 [1. 2.]
 [3. 2.]
 [2. 0.]
 [1. 0.]]


## Exercise 6

Find out if the vector represented by $(−16, 3, 5)$  is orthogonal to $a = (1, −3, 5)$ and $b = (2, −1, 7)$.




In [89]:
import numpy as np

v = np.array([-16, 3, 5])
a = np.array([1, -3, 5])
b = np.array([2, -1, 7])

dot_va = np.dot(v, a)
dot_vb = np.dot(v, b)

print(f"v ⋅ a = {dot_va}")
print(f"v ⋅ b = {dot_vb}")


if dot_va == 0 and dot_vb == 0:
    print("The vector v is orthogonal to both a and b.")


v ⋅ a = 0
v ⋅ b = 0
The vector v is orthogonal to both a and b.


## Exercise 7

Create the matrix $$\begin{bmatrix} 1 & 5 & 2 \\ 2 & 3 & -1 \\ 0 & 1 & -5 \end{bmatrix}$$

and compute its determinant and inverse. (use numpy function)

In [91]:
import numpy as np
A = np.array([
    [1, 5, 2],
    [2, 3, -1],
    [0, 1, -5]
])

det = np.linalg.det(A)

if det != 0:
    inv = np.linalg.inv(A)
    print("Determinant:", det)
    print("Inverse matrix:\n", inv)

Determinant: 40.000000000000014
Inverse matrix:
 [[-0.35   0.675 -0.275]
 [ 0.25  -0.125  0.125]
 [ 0.05  -0.025 -0.175]]


## Exercise 8

Given the two equations below, solve for $x_{1}$ and $x_{2}$ 

$x_{1} + 3x_{2} = 2$

$x_{1} + 2x_{2} = 0$

(Hint: Remember $AX = B$, use the linalg function from numpy)




In [92]:
import numpy as np

A = np.array([[1, 3],
              [1, 2]])

B = np.array([2, 0])

X = np.linalg.solve(A, B)

print("Solution:")
print(f"x1 = {X[0]}")
print(f"x2 = {X[1]}")

Solution:
x1 = -4.0
x2 = 2.0


## Exercise 9

Find the critical points of the function $f(x)= x^3−2x^2+x$ and use the second derivative test to find the maximum on interval $x⊂[0,1]$. 

**Hint 1**: remember the concepts of first differentiation and second differentiation;

**Hint 2**: `sympy` python library with use of `solve`, `diff`.

In [96]:
#!pip install sympy
import sympy as sp

x = sp.symbols('x')
f = x**3 - 2*x**2 + x

f_prime = sp.diff(f, x)
print("First derivative:", f_prime)

critical_points = sp.solve(f_prime, x)
print("Critical points:", critical_points)

f_double_prime = sp.diff(f_prime, x)
print("Second derivative:", f_double_prime)


for point in critical_points:
    if 0 <= point <= 1:
        second_derivative_value = f_double_prime.subs(x, point)
        nature = "Minimum" if second_derivative_value > 0 else "Maximum" if second_derivative_value < 0 else "Inconclusive"
        print(f"At x = {point}, f''(x) = {second_derivative_value} → {nature}")

# Evaluate endpoints as well
f_at_0 = f.subs(x, 0)
f_at_1 = f.subs(x, 1)
print(f"f(0) = {f_at_0}, f(1) = {f_at_1}")

First derivative: 3*x**2 - 4*x + 1
Critical points: [1/3, 1]
Second derivative: 6*x - 4
At x = 1/3, f''(x) = -2 → Maximum
At x = 1, f''(x) = 2 → Minimum
f(0) = 0, f(1) = 0


## Exercise 10

Maximise $f(x, y, z) = xy + yz$, subject to the constraints $x + 2y = 6$ and $x − 3z = 0$. 

**Hint 1**: set up the Lagrange equation, $f (x, y, z) − λ(constraint1) − μ(constraint2)$; 

**Hint 2**: Set partial derivatives to zero and solve the following set of equations; 

**Hint 3**: Use `solve`. 

In [100]:
#!pip install sympy
import sympy as sp
x, y, z, λ, μ = sp.symbols('x y z λ μ')
f = x*y + y*z

constraint1 = x + 2*y - 6
constraint2 = x - 3*z

# Lagrangian
L = f - λ * constraint1 - μ * constraint2

gradients = [
    sp.diff(L, var) for var in (x, y, z, λ, μ)
]

# Solve system of equations
solution = sp.solve(gradients, (x, y, z, λ, μ), dict=True)
print(solution)
# Evaluate function at optimal point
f_val = f.subs(solution[0])
print(f_val)


"""The point (x, y, z) that we found:
	•	Is the best combination of variables
	•	That respects the limits
	•	While giving us the highest possible result for our goal

"""

[{x: 3, y: 3/2, z: 1, λ: 2, μ: -1/2}]
6
